apiVersion: v1
kind: Service
metadata:
  name: springboot-svc-consumer
spec:
  type: NodePort
  selector:
    app: springboot-svc-consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080